const mrecbtn = document.querySelector('.my-btn')
const srecbtn = document.querySelector('.s-btn')
const lrecbtn = document.querySelector('.l-btn')

const mrec = document.querySelector('.my-collapse')
const srec = document.querySelector('.s-collapse')
const lrec = document.querySelector('.l-collapse')

mrecbtn.addEventListener('click', function showRecipe(){
    mrecbtn.classList.remove('muted')
    lrecbtn.classList.remove('highlighted')
    srecbtn.classList.remove('highlighted')
    mrec.classList.remove('hide')
    lrec.classList.remove('show')
    srec.classList.remove('show')
})
lrecbtn.addEventListener('click', function showRecipe(){
    mrecbtn.classList.add('muted')
    lrecbtn.classList.add('highlighted')
    srecbtn.classList.remove('highlighted')
    mrec.classList.add('hide')
    lrec.classList.add('show')
    srec.classList.remove('show')
})
srecbtn.addEventListener('click', function showRecipe(){
    mrecbtn.classList.add('muted')
    lrecbtn.classList.remove('highlighted')
    srecbtn.classList.add('highlighted')
    mrec.classList.add('hide')
    lrec.classList.remove('show')
    srec.classList.add('show')
})